### ISSUE TITLE
Make AppDelegate conform to AppKitDelegate

### ISSUE THREAD

**Issue by telip007** [pace/connectedfueling-app-ios#7]
Currently, the `AppKitDelegate` is only set in the `start()` method of `PaymentHistoryCoordinator` and otherwise nil. However, it should be set by app start to avoid unexpected behavior in the PWA <-> SDK communication. To fix this remove the `AppKitDelegate` conformance of `PaymentHistoryCoordinator` (since this is not needed here anyway) and instead let `AppDelegate` conform to the protocol and set it on `application(application:,didFinishLaunchingWithOptions:)`.

**Comment by EmDee** [comment]
@telip007 Can you take care of this in the next weeks, when you get the chance to? Please also update the SDK.

**Comment by telip007** [comment]
@EmDee will do it this week :)
